name: Notify by Email

on:
  workflow_dispatch:
  # 保留手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Tim-s-News

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 企业微信打卡
        body: file://email.txt
        to: 1216414009@qq.com
        from: GitHub Actions
